### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by builtbybasit** [paymennt/paymennt-php#1]
Could not find a version of package paymennt/paymennt-php matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

PHP Versions: 7.4
Composer Version: 2.1.12

![2022-04-12_16-27-46](https://user-images.githubusercontent.com/45251447/162950485-e3f193cd-9876-4ed4-9971-fc2d46609f46.jpg)

**Comment by abdullahkhan1214** [comment]
A stable version( v1.0.0 ) of the SDK has been released, which satisfies minimum-stability: stable. This shall solve the issue.
